lista = list(range(10))
print(lista)
lista.append(6)
print(lista)
lista.insert(2,7)
print(lista)
lista.remove(lista[3])
print(lista)
lista.append(4)
print(lista.count(4))

print(lista[:3])
print(lista[2:7])
print(lista[::3])
print(lista[-3:])
print(lista[:-4])
print(lista[5])
print(lista)
lista[6] = 12
print(lista)
lista.reverse()
print(lista)
lista.sort()
print(lista)